"""Patch catalog.py to add dynamic CSV import loader."""
import ast

with open('c:/InvenIQ/backend/app/api/catalog.py', 'rb') as f:
    data = f.read()

marker = b'def _get_all_products() -> List[dict]:\r\n    return CATALOG + _EBCO_CATALOG + _SANJAY_CATALOG + _RUNTIME_PRODUCTS'
pos = data.find(marker)
print(f"Marker found at byte: {pos}")
if pos < 0:
    print("ERROR: marker not found"); raise SystemExit(1)

new_code = (
    b"# -- Import catalog (loaded from product_imp_files/ at startup) ----\n"
    b"import os as _os, csv as _csv\n"
    b"from pathlib import Path as _Path\n"
    b"\n"
    b"_IMPORT_CATALOG: list = []\n"
    b"_import_load_status: dict = {'loaded': False, 'count': 0, 'files': [], 'error': ''}\n"
    b"\n"
    b"_EBCO_CATEGORY_HSN = {\n"
    b"    'Drawer Slides': '8302', 'Hinges': '8302',\n"
    b"    'Aluminium Profiles & Handles': '7604',\n"
    b"    'Furniture Locks': '8301', 'General Hardware': '8302',\n"
    b"    'Bed & Wardrobe Fittings': '8302', 'Bed Fittings': '8302',\n"
    b"    'Hi Slide Wardrobe Sliding Systems': '8302',\n"
    b"    'Kitchen - Drawer Systems & Accessories': '8302',\n"
    b"    'Kitchen - Storage Systems': '8302',\n"
    b"    'Kitchen - Corner Solutions': '8302',\n"
    b"    'Kitchen - Midway Systems': '8302',\n"
    b"    'Kitchen - Overhead Systems': '8302',\n"
    b"    'Kitchen - Waste Bins & More': '8302',\n"
    b"    'Window, Door & Glass Hardware': '8302',\n"
    b"    'Joinery Fittings & Screws': '7318',\n"
    b"    'Furniture Lights - LED': '9405',\n"
    b"    'ESmart Digital Locks': '8531',\n"
    b"    'Office Furniture Fittings': '8302',\n"
    b"    'Office - CPU Stands & Stations': '9403',\n"
    b"    'Office - Safe Drawers': '8303',\n"
    b"    'Office - Monitor Arms': '8302',\n"
    b"    'Office - Keyboard Station & Trays': '8302',\n"
    b"    'Office - Electric Boxes & Chargers': '8536',\n"
    b"    'Office - Furniture Essentials': '8302',\n"
    b"    'Retail Display Systems': '8302',\n"
    b"    'Speciality Locks': '8301', 'Premium Locks': '8301',\n"
    b"    'Secutek Locks': '8301', 'Target Locks': '8301',\n"
    b"    'Other Locks / Latches': '8301',\n"
    b"}\n"
    b"\n"
    b"\n"
    b"def _csv_row_to_product(row: dict, pid: int) -> dict:\n"
    b"    cat       = (row.get('Category') or '').strip()\n"
    b"    item_name = (row.get('Item Name') or '').strip()\n"
    b"    item_code = (row.get('Item Code') or '').strip()\n"
    b"    size_str  = (row.get('Size') or '').strip()\n"
    b"    finish    = (row.get('Finish') or '').strip()\n"
    b"    pcs_set   = (row.get('PCS / Set') or '').strip()\n"
    b"    spu_str   = (row.get('SPU') or '').strip()\n"
    b"    mrp_raw   = ''\n"
    b"    for k, v in row.items():\n"
    b"        if 'mrp' in k.lower() or ('price' in k.lower() and 'buy' not in k.lower()):\n"
    b"            mrp_raw = (v or '').strip().replace(',', '').replace(' ', '')\n"
    b"            if mrp_raw: break\n"
    b"    is_new = bool((row.get('New Product') or '').strip())\n"
    b"    try: mrp = float(mrp_raw) if mrp_raw else 0.0\n"
    b"    except ValueError: mrp = 0.0\n"
    b"    try: spu = int(float(spu_str)) if spu_str else 0\n"
    b"    except ValueError: spu = 0\n"
    b"    buy_price  = round(mrp * 0.65, 2)\n"
    b"    margin_pct = 35.0 if mrp > 0 else 0.0\n"
    b"    hsn  = _EBCO_CATEGORY_HSN.get(cat, '8302')\n"
    b"    tags = ['ebco', 'hardware']\n"
    b"    cl   = cat.lower()\n"
    b"    if 'drawer' in cl:  tags.append('drawer')\n"
    b"    if 'hinge'  in cl:  tags.append('hinge')\n"
    b"    if 'lock'   in cl:  tags.append('lock')\n"
    b"    if 'handle' in cl or 'profile' in cl: tags.append('handle')\n"
    b"    if 'slide'  in cl or 'sliding' in cl: tags.append('slide')\n"
    b"    if 'kitchen' in cl: tags.append('kitchen')\n"
    b"    if 'office'  in cl: tags.append('office')\n"
    b"    if finish: tags.append(finish.lower().replace('/', '-'))\n"
    b"    name = (f'{item_name} [{item_code}]'\n"
    b"            if item_code and item_code not in item_name else item_name)\n"
    b"    return {\n"
    b"        'product_id': pid, 'sku_code': item_code, 'item_code': item_code,\n"
    b"        'name': name, 'item_name': item_name, 'brand': 'Ebco',\n"
    b"        'category': cat, 'sub_category': finish or '',\n"
    b"        'size': size_str, 'finish': finish,\n"
    b"        'pcs_per_set': pcs_set, 'unit': pcs_set or 'Nos',\n"
    b"        'spu': spu, 'moq': spu or 1,\n"
    b"        'mrp': mrp, 'sell_price': mrp, 'buy_price': buy_price,\n"
    b"        'margin_pct': margin_pct, 'gst_rate': 18.0, 'hsn_code': hsn,\n"
    b"        'stock_status': 'in_stock', 'supplier': 'Ebco India Ltd',\n"
    b"        'is_new_product': is_new, 'specifications': size_str,\n"
    b"        'tags': tags, 'features': [], 'applications': [],\n"
    b"        'certifications': [], 'competitors': [],\n"
    b"    }\n"
    b"\n"
    b"\n"
    b"def _load_import_files(import_dir=None) -> int:\n"
    b"    global _import_load_status\n"
    b"    _IMPORT_CATALOG.clear()\n"
    b"    _import_load_status = {'loaded': False, 'count': 0, 'files': [], 'error': ''}\n"
    b"    base = (_Path(import_dir) if import_dir else\n"
    b"            _Path(__file__).parent.parent.parent.parent / 'product_imp_files')\n"
    b"    if not base.exists():\n"
    b"        _import_load_status['error'] = f'Directory not found: {base}'\n"
    b"        return 0\n"
    b"    pid   = 20001\n"
    b"    total = 0\n"
    b"    loaded_files: list = []\n"
    b"    for filepath in sorted(base.glob('*.csv')):\n"
    b"        try:\n"
    b"            rows = []\n"
    b"            for enc in ('utf-8-sig', 'utf-8', 'latin-1', 'cp1252'):\n"
    b"                try:\n"
    b"                    with open(filepath, 'r', encoding=enc, errors='replace') as fh:\n"
    b"                        rows = list(_csv.DictReader(fh))\n"
    b"                    break\n"
    b"                except Exception: continue\n"
    b"            count = 0\n"
    b"            for row in rows:\n"
    b"                p = _csv_row_to_product(row, pid)\n"
    b"                if not p['item_code'] and not p['item_name']: continue\n"
    b"                _IMPORT_CATALOG.append(p)\n"
    b"                pid += 1; count += 1\n"
    b"            if count:\n"
    b"                total += count\n"
    b"                loaded_files.append(f'{filepath.name} ({count})')\n"
    b"                logger.info('catalog: loaded %d from %s', count, filepath.name)\n"
    b"        except Exception as exc:\n"
    b"            logger.warning('catalog: CSV load failed %s -- %s', filepath.name, exc)\n"
    b"    try:\n"
    b"        import openpyxl as _xl\n"
    b"        for filepath in sorted(base.glob('*.xlsx')):\n"
    b"            try:\n"
    b"                wb = _xl.load_workbook(filepath, read_only=True, data_only=True)\n"
    b"                for ws in wb.worksheets:\n"
    b"                    headers: list = []\n"
    b"                    count = 0\n"
    b"                    for ri, row in enumerate(ws.iter_rows(values_only=True)):\n"
    b"                        if ri == 0:\n"
    b"                            headers = [str(c or '').strip() for c in row]\n"
    b"                            continue\n"
    b"                        if not any(row): continue\n"
    b"                        rd = {headers[i]: (str(v) if v is not None else '')\n"
    b"                              for i, v in enumerate(row) if i < len(headers)}\n"
    b"                        p = _csv_row_to_product(rd, pid)\n"
    b"                        if not p['item_code'] and not p['item_name']: continue\n"
    b"                        _IMPORT_CATALOG.append(p)\n"
    b"                        pid += 1; count += 1; total += 1\n"
    b"                    if count:\n"
    b"                        loaded_files.append(f'{filepath.name}/{ws.title} ({count})')\n"
    b"                        logger.info('catalog: loaded %d from %s/%s', count, filepath.name, ws.title)\n"
    b"            except Exception as exc:\n"
    b"                logger.warning('catalog: XLSX load failed %s -- %s', filepath.name, exc)\n"
    b"    except ImportError: pass\n"
    b"    _import_load_status = {\n"
    b"        'loaded': total > 0, 'count': total,\n"
    b"        'files': loaded_files,\n"
    b"        'error': '' if total > 0 else 'No products loaded',\n"
    b"    }\n"
    b"    logger.info('catalog: import load complete -- %d products, %d file(s)', total, len(loaded_files))\n"
    b"    return total\n"
    b"\n"
    b"\n"
    b"# Load at module import time\n"
    b"try:\n"
    b"    _load_import_files()\n"
    b"except Exception as _load_exc:\n"
    b"    logger.warning('catalog: import load failed at startup -- %s', _load_exc)\n"
    b"\n"
    b"\n"
    b"def _get_all_products() -> List[dict]:\n"
    b"    if _IMPORT_CATALOG:\n"
    b"        seen: set = set()\n"
    b"        merged: list = []\n"
    b"        for src in (_RUNTIME_PRODUCTS, _IMPORT_CATALOG, _EBCO_CATALOG, CATALOG, _SANJAY_CATALOG):\n"
    b"            for p in src:\n"
    b"                sku = p.get('sku_code', '') or str(p.get('product_id', ''))\n"
    b"                if sku and sku in seen: continue\n"
    b"                if sku: seen.add(sku)\n"
    b"                merged.append(p)\n"
    b"        return merged\n"
    b"    return CATALOG + _EBCO_CATALOG + _SANJAY_CATALOG + _RUNTIME_PRODUCTS\n"
)

fixed = data[:pos] + new_code + data[pos + len(marker):]

src = fixed.lstrip(b'\xef\xbb\xbf').decode('utf-8', errors='replace')
try:
    ast.parse(src)
    print("Syntax OK")
    with open('c:/InvenIQ/backend/app/api/catalog.py', 'wb') as f:
        f.write(fixed)
    print("File written successfully")
except SyntaxError as e:
    print(f"Syntax error at line {e.lineno}: {e.msg}")
    lines = src.split('\n')
    for i in range(max(0, e.lineno-3), min(len(lines), e.lineno+3)):
        print(f"  {i+1}: {lines[i]}")
