"""
Sanjay Hardware — Complete Product Catalog
All hardware, sanitary, plumbing, CP fittings, and building material products.
Product IDs start at 5001 to avoid conflicts with existing catalog.
"""

SANJAY_HARDWARE_CATALOG = [

    # ═══════════════════════════════════════════════════════════
    # CP FITTINGS — JAQUAR / CERA / HINDWARE / KOHLER RANGE
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5001, "sku_code": "SH-CPF-001",
        "name": "Jaquar Florentine Single Lever Basin Mixer (Chrome)",
        "brand": "Jaquar", "category": "CP Fittings", "sub_category": "Basin Mixer",
        "unit": "Nos", "size": "Standard", "finish": "Chrome",
        "buy_price": 2800, "sell_price": 3850, "margin_pct": 27.3,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "Hot & cold, wall-mounted, 35mm ceramic cartridge, 5-year warranty",
        "stock_status": "in_stock", "tags": ["cp_fittings", "jaquar", "basin"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5002, "sku_code": "SH-CPF-002",
        "name": "Jaquar Overhead Shower 6\" Round with SS Arm (Chrome)",
        "brand": "Jaquar", "category": "CP Fittings", "sub_category": "Shower",
        "unit": "Set", "size": "6 inch / 450mm arm", "finish": "Chrome",
        "buy_price": 1400, "sell_price": 1980, "margin_pct": 29.3,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "ABS shower head, SS arm 450mm, rubber nozzles, anti-calc",
        "stock_status": "in_stock", "tags": ["cp_fittings", "jaquar", "shower"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5003, "sku_code": "SH-CPF-003",
        "name": "Jaquar Health Faucet with 1m SS Hose (Chrome)",
        "brand": "Jaquar", "category": "CP Fittings", "sub_category": "Health Faucet",
        "unit": "Set", "size": "1 metre hose", "finish": "Chrome",
        "buy_price": 420, "sell_price": 620, "margin_pct": 32.3,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "ABS body, SS flexible hose 1m, wall hook included",
        "stock_status": "in_stock", "tags": ["cp_fittings", "jaquar", "health_faucet"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5004, "sku_code": "SH-CPF-004",
        "name": "Cera Single Lever Kitchen Mixer (Chrome)",
        "brand": "Cera", "category": "CP Fittings", "sub_category": "Kitchen Mixer",
        "unit": "Nos", "size": "Standard", "finish": "Chrome",
        "buy_price": 1600, "sell_price": 2200, "margin_pct": 27.3,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "High-arc spout, 360° swivel, ceramic cartridge, flow aerator",
        "stock_status": "in_stock", "tags": ["cp_fittings", "cera", "kitchen"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5005, "sku_code": "SH-CPF-005",
        "name": "Hindware Stop Cock (Chrome, 15mm)",
        "brand": "Hindware", "category": "CP Fittings", "sub_category": "Stop Cock",
        "unit": "Nos", "size": "15mm", "finish": "Chrome",
        "buy_price": 180, "sell_price": 260, "margin_pct": 30.8,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "Brass body, ceramic disc, quarter-turn operation",
        "stock_status": "in_stock", "tags": ["cp_fittings", "hindware", "stop_cock"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5006, "sku_code": "SH-CPF-006",
        "name": "Jaquar Angle Valve (Chrome, 15mm)",
        "brand": "Jaquar", "category": "CP Fittings", "sub_category": "Angle Valve",
        "unit": "Nos", "size": "15mm", "finish": "Chrome",
        "buy_price": 220, "sell_price": 320, "margin_pct": 31.3,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "Brass body, 1/4-turn ceramic disc, connections ½″ × ½″",
        "stock_status": "in_stock", "tags": ["cp_fittings", "jaquar", "angle_valve"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5007, "sku_code": "SH-CPF-007",
        "name": "Kohler Alteo Single Lever Basin Mixer (Chrome)",
        "brand": "Kohler", "category": "CP Fittings", "sub_category": "Basin Mixer",
        "unit": "Nos", "size": "Standard", "finish": "Chrome",
        "buy_price": 4200, "sell_price": 6500, "margin_pct": 35.4,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "Premium range, 35mm cartridge, pop-up drain included, 7-year warranty",
        "stock_status": "in_stock", "tags": ["cp_fittings", "kohler", "premium"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5008, "sku_code": "SH-CPF-008",
        "name": "Essco Bib Cock Wall Mounted (Chrome, 15mm)",
        "brand": "Essco", "category": "CP Fittings", "sub_category": "Bib Cock",
        "unit": "Nos", "size": "15mm", "finish": "Chrome",
        "buy_price": 280, "sell_price": 390, "margin_pct": 28.2,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "Brass body, wall-mounted, rubber washer seat",
        "stock_status": "in_stock", "tags": ["cp_fittings", "essco", "bib_cock"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # SANITARY WARE
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5010, "sku_code": "SH-SAW-001",
        "name": "Hindware Queo Wall-Hung EWC with Soft-Close Seat",
        "brand": "Hindware", "category": "Sanitary Ware", "sub_category": "EWC",
        "unit": "Set", "size": "Standard", "finish": "White",
        "buy_price": 8500, "sell_price": 12000, "margin_pct": 29.2,
        "gst_rate": 18.0, "hsn_code": "6910",
        "specifications": "Dual flush 3/6L, concealed cistern, soft-close PP seat, S-trap",
        "stock_status": "in_stock", "tags": ["sanitary", "hindware", "ewc", "wall_hung"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5011, "sku_code": "SH-SAW-002",
        "name": "Parryware Calla Two-Piece WC (White)",
        "brand": "Parryware", "category": "Sanitary Ware", "sub_category": "WC",
        "unit": "Set", "size": "S-trap 300mm", "finish": "White",
        "buy_price": 4200, "sell_price": 5800, "margin_pct": 27.6,
        "gst_rate": 18.0, "hsn_code": "6910",
        "specifications": "Two-piece, S-trap, 6L flush, white, PP seat included",
        "stock_status": "in_stock", "tags": ["sanitary", "parryware", "wc"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5012, "sku_code": "SH-SAW-003",
        "name": "Kohler Veil Wall-Hung EWC with Slim Seat",
        "brand": "Kohler", "category": "Sanitary Ware", "sub_category": "EWC",
        "unit": "Set", "size": "Standard", "finish": "White",
        "buy_price": 18000, "sell_price": 28000, "margin_pct": 35.7,
        "gst_rate": 18.0, "hsn_code": "6910",
        "specifications": "Wall-hung, dual flush, elongated bowl, slow-close seat",
        "stock_status": "in_stock", "tags": ["sanitary", "kohler", "premium", "ewc"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5013, "sku_code": "SH-SAW-004",
        "name": "Hindware Pedestal Wash Basin (White, 450mm)",
        "brand": "Hindware", "category": "Sanitary Ware", "sub_category": "Wash Basin",
        "unit": "Set", "size": "450 × 300mm", "finish": "White",
        "buy_price": 2800, "sell_price": 3900, "margin_pct": 28.2,
        "gst_rate": 18.0, "hsn_code": "6910",
        "specifications": "Pedestal type, vitreous china, 450mm, tap hole included",
        "stock_status": "in_stock", "tags": ["sanitary", "hindware", "wash_basin"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5014, "sku_code": "SH-SAW-005",
        "name": "Cera Counter-Top Wash Basin (White, 560mm)",
        "brand": "Cera", "category": "Sanitary Ware", "sub_category": "Wash Basin",
        "unit": "Nos", "size": "560 × 380mm", "finish": "White",
        "buy_price": 3200, "sell_price": 4500, "margin_pct": 28.9,
        "gst_rate": 18.0, "hsn_code": "6910",
        "specifications": "Counter-top, vitreous china, no overflow, tap hole centre",
        "stock_status": "in_stock", "tags": ["sanitary", "cera", "wash_basin", "counter"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # BATHROOM ACCESSORIES
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5020, "sku_code": "SH-BAC-001",
        "name": "Jaquar 5-Piece Bathroom Accessories Set (Chrome)",
        "brand": "Jaquar", "category": "Bathroom Accessories", "sub_category": "Accessory Set",
        "unit": "Set", "size": "Standard", "finish": "Chrome",
        "buy_price": 1800, "sell_price": 2600, "margin_pct": 30.8,
        "gst_rate": 18.0, "hsn_code": "3922",
        "specifications": "Towel bar 24\", towel ring, robe hook, soap dish, toilet paper holder",
        "stock_status": "in_stock", "tags": ["bathroom_accessories", "jaquar"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5021, "sku_code": "SH-BAC-002",
        "name": "Towel Bar SS 24 inch (Chrome)",
        "brand": "Hindware", "category": "Bathroom Accessories", "sub_category": "Towel Bar",
        "unit": "Nos", "size": "24 inch (600mm)", "finish": "Chrome",
        "buy_price": 380, "sell_price": 550, "margin_pct": 30.9,
        "gst_rate": 18.0, "hsn_code": "3922",
        "specifications": "Stainless steel 304, wall-mounted, zinc alloy brackets",
        "stock_status": "in_stock", "tags": ["bathroom_accessories", "towel_bar"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5022, "sku_code": "SH-BAC-003",
        "name": "LED Mirror with Touch Dimmer (60×80cm)",
        "brand": "Hindware", "category": "Bathroom Accessories", "sub_category": "Mirror",
        "unit": "Nos", "size": "600 × 800mm", "finish": "Silver",
        "buy_price": 3200, "sell_price": 4800, "margin_pct": 33.3,
        "gst_rate": 18.0, "hsn_code": "7009",
        "specifications": "LED backlit, touch dimmer, IP44, 6500K, frameless",
        "stock_status": "in_stock", "tags": ["bathroom_accessories", "led_mirror"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5023, "sku_code": "SH-BAC-004",
        "name": "Shower Enclosure Frameless Toughened Glass (900×900mm)",
        "brand": "Parryware", "category": "Bathroom Accessories", "sub_category": "Shower Enclosure",
        "unit": "Nos", "size": "900 × 900 × 2000mm", "finish": "Chrome",
        "buy_price": 12000, "sell_price": 17500, "margin_pct": 31.4,
        "gst_rate": 18.0, "hsn_code": "3922",
        "specifications": "8mm toughened glass, frameless, sliding door, anti-lime coating",
        "stock_status": "in_stock", "tags": ["bathroom_accessories", "shower_enclosure"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5024, "sku_code": "SH-BAC-005",
        "name": "Floor Drain SS 4\" Square with Anti-Odour Trap",
        "brand": "Hindware", "category": "Bathroom Accessories", "sub_category": "Floor Drain",
        "unit": "Nos", "size": "4 inch (100mm)", "finish": "SS Brushed",
        "buy_price": 280, "sell_price": 420, "margin_pct": 33.3,
        "gst_rate": 18.0, "hsn_code": "3922",
        "specifications": "SS 304, water seal trap, removable strainer, 32mm outlet",
        "stock_status": "in_stock", "tags": ["bathroom_accessories", "floor_drain"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # PLUMBING — PIPES & FITTINGS
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5030, "sku_code": "SH-PLM-001",
        "name": "Astral CPVC Pipe 15mm (Hot & Cold)",
        "brand": "Astral", "category": "Plumbing", "sub_category": "CPVC Pipe",
        "unit": "Mtr", "size": "15mm × 3m length", "finish": "-",
        "buy_price": 52, "sell_price": 72, "margin_pct": 27.8,
        "gst_rate": 18.0, "hsn_code": "3917",
        "specifications": "CPVC, hot & cold water, 1.0 MPa, IS 15778, 3m length",
        "stock_status": "in_stock", "tags": ["plumbing", "astral", "cpvc_pipe"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5031, "sku_code": "SH-PLM-002",
        "name": "Astral CPVC Pipe 20mm (Hot & Cold)",
        "brand": "Astral", "category": "Plumbing", "sub_category": "CPVC Pipe",
        "unit": "Mtr", "size": "20mm × 3m length", "finish": "-",
        "buy_price": 78, "sell_price": 108, "margin_pct": 27.8,
        "gst_rate": 18.0, "hsn_code": "3917",
        "specifications": "CPVC, 20mm, 1.0 MPa, IS 15778, 3m length",
        "stock_status": "in_stock", "tags": ["plumbing", "astral", "cpvc_pipe"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5032, "sku_code": "SH-PLM-003",
        "name": "Supreme PVC SWR Pipe 110mm (4 inch)",
        "brand": "Supreme", "category": "Plumbing", "sub_category": "SWR Pipe",
        "unit": "Mtr", "size": "110mm × 3m length", "finish": "-",
        "buy_price": 180, "sell_price": 245, "margin_pct": 26.5,
        "gst_rate": 18.0, "hsn_code": "3917",
        "specifications": "PVC SWR, 110mm (4\"), IS 13592, 3m length, grey",
        "stock_status": "in_stock", "tags": ["plumbing", "supreme", "swr_pipe"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5033, "sku_code": "SH-PLM-004",
        "name": "Zoloto Ball Valve 15mm (Brass, PN25)",
        "brand": "Zoloto", "category": "Plumbing", "sub_category": "Ball Valve",
        "unit": "Nos", "size": "15mm (½ inch)", "finish": "Nickel Plated",
        "buy_price": 120, "sell_price": 175, "margin_pct": 31.4,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "Brass body, PTFE seats, PN25, ISI marked, 1/4-turn operation",
        "stock_status": "in_stock", "tags": ["plumbing", "zoloto", "ball_valve"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5034, "sku_code": "SH-PLM-005",
        "name": "Zoloto Ball Valve 25mm (Brass, PN25)",
        "brand": "Zoloto", "category": "Plumbing", "sub_category": "Ball Valve",
        "unit": "Nos", "size": "25mm (1 inch)", "finish": "Nickel Plated",
        "buy_price": 220, "sell_price": 310, "margin_pct": 29.0,
        "gst_rate": 18.0, "hsn_code": "8481",
        "specifications": "Brass body, PTFE seats, PN25, full bore, ISI marked",
        "stock_status": "in_stock", "tags": ["plumbing", "zoloto", "ball_valve"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5035, "sku_code": "SH-PLM-006",
        "name": "CPVC Elbow 90° 15mm (Astral)",
        "brand": "Astral", "category": "Plumbing", "sub_category": "CPVC Fitting",
        "unit": "Nos", "size": "15mm", "finish": "-",
        "buy_price": 18, "sell_price": 26, "margin_pct": 30.8,
        "gst_rate": 18.0, "hsn_code": "3917",
        "specifications": "CPVC, 15mm, 90° elbow, socket-socket, IS 15778",
        "stock_status": "in_stock", "tags": ["plumbing", "astral", "cpvc_fitting"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5036, "sku_code": "SH-PLM-007",
        "name": "CPVC Tee 15mm (Astral)",
        "brand": "Astral", "category": "Plumbing", "sub_category": "CPVC Fitting",
        "unit": "Nos", "size": "15mm", "finish": "-",
        "buy_price": 22, "sell_price": 32, "margin_pct": 31.3,
        "gst_rate": 18.0, "hsn_code": "3917",
        "specifications": "CPVC, 15mm equal tee, three socket outlets",
        "stock_status": "in_stock", "tags": ["plumbing", "astral", "cpvc_fitting"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # DOOR HARDWARE — HINGES
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5040, "sku_code": "SH-HNG-001",
        "name": "Hettich Sensys Soft-Close Hinge (Full Overlay)",
        "brand": "Hettich", "category": "Hardware Hinges", "sub_category": "Cabinet Hinge",
        "unit": "Nos", "size": "Full overlay, 110°", "finish": "Nickel Matt",
        "buy_price": 85, "sell_price": 120, "margin_pct": 29.2,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Soft-close integrated, clip-top, 110°, full overlay, tool-free removal",
        "stock_status": "in_stock", "tags": ["hardware", "hettich", "hinge", "soft_close"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5041, "sku_code": "SH-HNG-002",
        "name": "Hettich Sensys Soft-Close Hinge (Half Overlay)",
        "brand": "Hettich", "category": "Hardware Hinges", "sub_category": "Cabinet Hinge",
        "unit": "Nos", "size": "Half overlay, 110°", "finish": "Nickel Matt",
        "buy_price": 85, "sell_price": 120, "margin_pct": 29.2,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Soft-close integrated, clip-top, 110°, half overlay",
        "stock_status": "in_stock", "tags": ["hardware", "hettich", "hinge"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5042, "sku_code": "SH-HNG-003",
        "name": "Ebco Soft-Close Hinge Full Overlay (Set of 2)",
        "brand": "Ebco", "category": "Hardware Hinges", "sub_category": "Cabinet Hinge",
        "unit": "Set", "size": "Full overlay", "finish": "Nickel",
        "buy_price": 120, "sell_price": 165, "margin_pct": 27.3,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Soft-close, 110°, full overlay, pair with mounting plate",
        "stock_status": "in_stock", "tags": ["hardware", "ebco", "hinge"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5043, "sku_code": "SH-HNG-004",
        "name": "Butt Hinge SS 3\" (Pair)",
        "brand": "Dorset", "category": "Hardware Hinges", "sub_category": "Butt Hinge",
        "unit": "Pair", "size": "3 inch (75mm)", "finish": "SS Satin",
        "buy_price": 60, "sell_price": 88, "margin_pct": 31.8,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "SS 304, ball-bearing, 3\", reversible, 2 pairs per set",
        "stock_status": "in_stock", "tags": ["hardware", "butt_hinge", "ss"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # DRAWER CHANNELS & SLIDES
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5050, "sku_code": "SH-DRW-001",
        "name": "Hettich Soft-Close Drawer Channel 400mm (Pair)",
        "brand": "Hettich", "category": "Hardware Channels", "sub_category": "Drawer Slide",
        "unit": "Pair", "size": "400mm, Load: 30kg", "finish": "White",
        "buy_price": 280, "sell_price": 395, "margin_pct": 29.1,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Full extension, soft-close, 400mm, 30kg load, side-mount",
        "stock_status": "in_stock", "tags": ["hardware", "hettich", "drawer_channel"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5051, "sku_code": "SH-DRW-002",
        "name": "Hettich Soft-Close Drawer Channel 500mm (Pair)",
        "brand": "Hettich", "category": "Hardware Channels", "sub_category": "Drawer Slide",
        "unit": "Pair", "size": "500mm, Load: 30kg", "finish": "White",
        "buy_price": 320, "sell_price": 450, "margin_pct": 28.9,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Full extension, soft-close, 500mm, 30kg load",
        "stock_status": "in_stock", "tags": ["hardware", "hettich", "drawer_channel"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5052, "sku_code": "SH-DRW-003",
        "name": "Ebco Bottom-Mount Drawer Slide 400mm (Set of 4)",
        "brand": "Ebco", "category": "Hardware Channels", "sub_category": "Bottom Mount Slide",
        "unit": "Set", "size": "400mm, Load: 20kg", "finish": "IV",
        "buy_price": 185, "sell_price": 260, "margin_pct": 28.8,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Bottom-mount, 400mm, 20kg load, set of 4 pieces",
        "stock_status": "in_stock", "tags": ["hardware", "ebco", "drawer_slide"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # HANDLES & KNOBS
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5060, "sku_code": "SH-HDL-001",
        "name": "Hafele Bow Handle SS 96mm CC (Matt Black)",
        "brand": "Hafele", "category": "Hardware Handles", "sub_category": "Cabinet Handle",
        "unit": "Nos", "size": "CC: 96mm, L: 130mm", "finish": "Matt Black",
        "buy_price": 180, "sell_price": 260, "margin_pct": 30.8,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "SS 304, 96mm CC, matt black powder coat, M4 screws included",
        "stock_status": "in_stock", "tags": ["hardware", "hafele", "handle"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5061, "sku_code": "SH-HDL-002",
        "name": "Hafele Bow Handle SS 128mm CC (Brushed Nickel)",
        "brand": "Hafele", "category": "Hardware Handles", "sub_category": "Cabinet Handle",
        "unit": "Nos", "size": "CC: 128mm, L: 165mm", "finish": "Brushed Nickel",
        "buy_price": 210, "sell_price": 300, "margin_pct": 30.0,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "SS 304, 128mm CC, brushed nickel finish",
        "stock_status": "in_stock", "tags": ["hardware", "hafele", "handle"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5062, "sku_code": "SH-HDL-003",
        "name": "Gola Profile Handle Aluminium (Gold, per metre)",
        "brand": "Ebco", "category": "Hardware Handles", "sub_category": "Profile Handle",
        "unit": "Mtr", "size": "Per metre, H: 18mm", "finish": "Gold",
        "buy_price": 280, "sell_price": 400, "margin_pct": 30.0,
        "gst_rate": 18.0, "hsn_code": "7610",
        "specifications": "Aluminium extrusion gola profile, 18mm height, sold per metre, cut to size",
        "stock_status": "in_stock", "tags": ["hardware", "ebco", "gola_handle", "profile"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5063, "sku_code": "SH-HDL-004",
        "name": "Gola Profile Handle Aluminium (Silver, per metre)",
        "brand": "Ebco", "category": "Hardware Handles", "sub_category": "Profile Handle",
        "unit": "Mtr", "size": "Per metre, H: 18mm", "finish": "Silver",
        "buy_price": 250, "sell_price": 360, "margin_pct": 30.6,
        "gst_rate": 18.0, "hsn_code": "7610",
        "specifications": "Aluminium extrusion gola profile, silver anodised, 18mm height",
        "stock_status": "in_stock", "tags": ["hardware", "ebco", "gola_handle", "profile"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # LOCKS — MORTISE & CYLINDRICAL
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5070, "sku_code": "SH-LCK-001",
        "name": "Godrej Ultra Ultralocker Mortise Lock Set",
        "brand": "Godrej", "category": "Furniture Locks", "sub_category": "Mortise Lock",
        "unit": "Set", "size": "60mm backset", "finish": "SS Satin",
        "buy_price": 1400, "sell_price": 1950, "margin_pct": 28.2,
        "gst_rate": 18.0, "hsn_code": "8301",
        "specifications": "Mortise lock, 60mm backset, 3-lever mechanism, handle + key set",
        "stock_status": "in_stock", "tags": ["hardware", "godrej", "mortise_lock"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5071, "sku_code": "SH-LCK-002",
        "name": "Ebco Cabinet Lock 25mm (Cam Lock)",
        "brand": "Ebco", "category": "Furniture Locks", "sub_category": "Cam Lock",
        "unit": "Nos", "size": "25mm, for panel 15-19mm", "finish": "Nickel",
        "buy_price": 35, "sell_price": 55, "margin_pct": 36.4,
        "gst_rate": 18.0, "hsn_code": "8301",
        "specifications": "Zinc die-cast, 2 keys included, 90° operation, panel 15-19mm",
        "stock_status": "in_stock", "tags": ["hardware", "ebco", "cam_lock"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5072, "sku_code": "SH-LCK-003",
        "name": "Hettich Tower Bolt SS 200mm",
        "brand": "Hettich", "category": "Hardware Locks", "sub_category": "Tower Bolt",
        "unit": "Nos", "size": "200mm (8 inch)", "finish": "SS Satin",
        "buy_price": 95, "sell_price": 135, "margin_pct": 29.6,
        "gst_rate": 18.0, "hsn_code": "8301",
        "specifications": "SS 304, 200mm, flush fitting, smooth operation",
        "stock_status": "in_stock", "tags": ["hardware", "hettich", "tower_bolt"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5073, "sku_code": "SH-LCK-004",
        "name": "Dorset Door Closer (Size 3, SS Body)",
        "brand": "Dorset", "category": "Hardware Locks", "sub_category": "Door Closer",
        "unit": "Nos", "size": "Size 3 (up to 80kg)", "finish": "SS Satin",
        "buy_price": 850, "sell_price": 1200, "margin_pct": 29.2,
        "gst_rate": 18.0, "hsn_code": "8301",
        "specifications": "Hydraulic, adjustable closing speed, for doors up to 80kg",
        "stock_status": "in_stock", "tags": ["hardware", "dorset", "door_closer"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # WATERPROOFING & TILE GROUT
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5080, "sku_code": "SH-WPF-001",
        "name": "Dr. Fixit Raincoat Waterproofing Coat (20 Litre)",
        "brand": "Dr. Fixit", "category": "Waterproofing", "sub_category": "Exterior Coat",
        "unit": "Bucket", "size": "20 Litre", "finish": "White / Terracotta",
        "buy_price": 2200, "sell_price": 3100, "margin_pct": 29.0,
        "gst_rate": 18.0, "hsn_code": "3214",
        "specifications": "Acrylic, 2-coat system, 7-year warranty, coverage 6–8 sqm/litre",
        "stock_status": "in_stock", "tags": ["waterproofing", "dr_fixit", "exterior"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5081, "sku_code": "SH-WPF-002",
        "name": "Dr. Fixit Bathseal Bathroom Waterproofing (4 Litre)",
        "brand": "Dr. Fixit", "category": "Waterproofing", "sub_category": "Bathroom",
        "unit": "Can", "size": "4 Litre", "finish": "-",
        "buy_price": 780, "sell_price": 1100, "margin_pct": 29.1,
        "gst_rate": 18.0, "hsn_code": "3214",
        "specifications": "Polymer-modified, bathroom & wet area use, 5-year warranty",
        "stock_status": "in_stock", "tags": ["waterproofing", "dr_fixit", "bathroom"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5082, "sku_code": "SH-WPF-003",
        "name": "Fosroc Terrace Waterproofing System (20 Litre)",
        "brand": "Fosroc", "category": "Waterproofing", "sub_category": "Terrace",
        "unit": "Bucket", "size": "20 Litre", "finish": "Grey",
        "buy_price": 3200, "sell_price": 4500, "margin_pct": 28.9,
        "gst_rate": 18.0, "hsn_code": "3214",
        "specifications": "Polyurethane, single component, terrace & roof, 10-year warranty",
        "stock_status": "in_stock", "tags": ["waterproofing", "fosroc", "terrace"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # ADHESIVES & SEALANTS
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5090, "sku_code": "SH-ADH-001",
        "name": "Fevicol SH White Adhesive (5 Kg)",
        "brand": "Fevicol", "category": "Adhesives", "sub_category": "White Glue",
        "unit": "Can", "size": "5 Kg", "finish": "-",
        "buy_price": 380, "sell_price": 520, "margin_pct": 26.9,
        "gst_rate": 18.0, "hsn_code": "3506",
        "specifications": "Water-based PVA, woodworking grade, interior use",
        "stock_status": "in_stock", "tags": ["adhesive", "fevicol", "woodworking"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5091, "sku_code": "SH-ADH-002",
        "name": "Pidilite Silicone Sealant Clear (300ml)",
        "brand": "Pidilite", "category": "Adhesives", "sub_category": "Silicone Sealant",
        "unit": "Tube", "size": "300ml cartridge", "finish": "Clear",
        "buy_price": 120, "sell_price": 175, "margin_pct": 31.4,
        "gst_rate": 18.0, "hsn_code": "3506",
        "specifications": "Neutral cure, glass & sanitary use, waterproof, -40°C to +200°C",
        "stock_status": "in_stock", "tags": ["adhesive", "sealant", "silicone"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5092, "sku_code": "SH-ADH-003",
        "name": "Pidilite Silicone Sealant White (300ml)",
        "brand": "Pidilite", "category": "Adhesives", "sub_category": "Silicone Sealant",
        "unit": "Tube", "size": "300ml cartridge", "finish": "White",
        "buy_price": 120, "sell_price": 175, "margin_pct": 31.4,
        "gst_rate": 18.0, "hsn_code": "3506",
        "specifications": "Neutral cure, sanitary white, bathroom & kitchen use",
        "stock_status": "in_stock", "tags": ["adhesive", "sealant", "silicone"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # TILES
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5100, "sku_code": "SH-TIL-001",
        "name": "Kajaria Ceramic Wall Tile 300×600mm (per box)",
        "brand": "Kajaria", "category": "Tiles", "sub_category": "Wall Tile",
        "unit": "Box", "size": "300 × 600mm, 8 pcs/box = 1.44 sqm", "finish": "Matt",
        "buy_price": 580, "sell_price": 820, "margin_pct": 29.3,
        "gst_rate": 18.0, "hsn_code": "6907",
        "specifications": "Ceramic, 300×600mm, 8mm thick, 1.44 sqm/box, ISI marked",
        "stock_status": "in_stock", "tags": ["tiles", "kajaria", "wall_tile"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5101, "sku_code": "SH-TIL-002",
        "name": "Somany Vitrified Floor Tile 600×600mm (per box)",
        "brand": "Somany", "category": "Tiles", "sub_category": "Floor Tile",
        "unit": "Box", "size": "600 × 600mm, 4 pcs/box = 1.44 sqm", "finish": "Polished",
        "buy_price": 1100, "sell_price": 1550, "margin_pct": 29.0,
        "gst_rate": 18.0, "hsn_code": "6907",
        "specifications": "GVT, 600×600mm, 9mm thick, 1.44 sqm/box, R9 slip resistance",
        "stock_status": "in_stock", "tags": ["tiles", "somany", "floor_tile"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5102, "sku_code": "SH-TIL-003",
        "name": "Johnson Bathroom Ceramic Tile 300×300mm Anti-Skid (per box)",
        "brand": "Johnson", "category": "Tiles", "sub_category": "Bathroom Tile",
        "unit": "Box", "size": "300 × 300mm, 16 pcs/box = 1.44 sqm", "finish": "Anti-skid",
        "buy_price": 520, "sell_price": 730, "margin_pct": 28.8,
        "gst_rate": 18.0, "hsn_code": "6907",
        "specifications": "Ceramic, 300×300mm, anti-skid, bathroom floor use, R11 rating",
        "stock_status": "in_stock", "tags": ["tiles", "johnson", "bathroom_tile"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # GENERAL HARDWARE
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5110, "sku_code": "SH-GHW-001",
        "name": "SS Screws Countersunk 4×35mm (Box of 100)",
        "brand": "Dorset", "category": "General Hardware", "sub_category": "Screws",
        "unit": "Box", "size": "4 × 35mm, box of 100", "finish": "SS Zinc Plated",
        "buy_price": 80, "sell_price": 115, "margin_pct": 30.4,
        "gst_rate": 18.0, "hsn_code": "7318",
        "specifications": "SS 304, CSK Phillips head, 4×35mm, box of 100",
        "stock_status": "in_stock", "tags": ["general_hardware", "screws"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5111, "sku_code": "SH-GHW-002",
        "name": "Rawl Plug Wall Anchor 6mm (Pack of 100)",
        "brand": "Fischer", "category": "General Hardware", "sub_category": "Wall Anchors",
        "unit": "Pack", "size": "6mm, pack of 100", "finish": "-",
        "buy_price": 60, "sell_price": 88, "margin_pct": 31.8,
        "gst_rate": 18.0, "hsn_code": "7318",
        "specifications": "Nylon, 6mm, for brick/concrete, 25mm depth",
        "stock_status": "in_stock", "tags": ["general_hardware", "wall_anchor"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5112, "sku_code": "SH-GHW-003",
        "name": "Magnetic Catch / Door Latch (Pack of 10)",
        "brand": "Ebco", "category": "General Hardware", "sub_category": "Magnetic Catch",
        "unit": "Pack", "size": "Standard, pack of 10", "finish": "White",
        "buy_price": 120, "sell_price": 175, "margin_pct": 31.4,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Magnetic catch 3kg holding force, cabinet & wardrobe use",
        "stock_status": "in_stock", "tags": ["general_hardware", "magnetic_catch"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5113, "sku_code": "SH-GHW-004",
        "name": "Furniture Connector Cam Lock 15mm (Pack of 50)",
        "brand": "Hettich", "category": "General Hardware", "sub_category": "Connector",
        "unit": "Pack", "size": "15mm barrel, pack of 50", "finish": "Nickel",
        "buy_price": 180, "sell_price": 260, "margin_pct": 30.8,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Two-part cam lock connector, 15mm barrel, M6 bolt included",
        "stock_status": "in_stock", "tags": ["general_hardware", "cam_lock", "connector"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5114, "sku_code": "SH-GHW-005",
        "name": "Adjustable Cabinet Leg 100mm (Pack of 4)",
        "brand": "Ebco", "category": "General Hardware", "sub_category": "Cabinet Leg",
        "unit": "Pack", "size": "80–120mm adjustable, pack of 4", "finish": "White",
        "buy_price": 120, "sell_price": 175, "margin_pct": 31.4,
        "gst_rate": 18.0, "hsn_code": "8302",
        "specifications": "Plastic, adjustable 80–120mm, 80kg load per leg, snap-on plinth clip",
        "stock_status": "in_stock", "tags": ["general_hardware", "cabinet_leg"],
        "supplier": "Sanjay Hardware",
    },

    # ═══════════════════════════════════════════════════════════
    # ELECTRICAL CONDUIT & ACCESSORIES
    # ═══════════════════════════════════════════════════════════
    {
        "product_id": 5120, "sku_code": "SH-ELC-001",
        "name": "Finolex Rigid PVC Conduit 20mm (3m length)",
        "brand": "Finolex", "category": "Electrical", "sub_category": "Conduit",
        "unit": "Length", "size": "20mm × 3m", "finish": "Off-White",
        "buy_price": 55, "sell_price": 78, "margin_pct": 29.5,
        "gst_rate": 18.0, "hsn_code": "3917",
        "specifications": "UPVC, 20mm, IS 14930, rigid, 3m length, IS marked",
        "stock_status": "in_stock", "tags": ["electrical", "finolex", "conduit"],
        "supplier": "Sanjay Hardware",
    },
    {
        "product_id": 5121, "sku_code": "SH-ELC-002",
        "name": "MS Junction Box 3×3 inch (Surface)",
        "brand": "Legrand", "category": "Electrical", "sub_category": "Junction Box",
        "unit": "Nos", "size": "75 × 75 × 60mm", "finish": "Grey Powder Coat",
        "buy_price": 95, "sell_price": 135, "margin_pct": 29.6,
        "gst_rate": 18.0, "hsn_code": "8537",
        "specifications": "MS powder coated, surface mounting, 4 knock-outs, IP44",
        "stock_status": "in_stock", "tags": ["electrical", "junction_box"],
        "supplier": "Sanjay Hardware",
    },
]
